// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVXfQxBMUpSm_O54zn6w3NGCvhwcrqYAQ',
    appId: '1:879677984368:android:96b37a3911e24fd5302eb5',
    messagingSenderId: '879677984368',
    projectId: 'edapt-63485',
    storageBucket: 'edapt-63485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHiJfNTzpyqdwLpdyuWukiTBjnwQigaLI',
    appId: '1:879677984368:ios:371ba7e17060d6e4302eb5',
    messagingSenderId: '879677984368',
    projectId: 'edapt-63485',
    storageBucket: 'edapt-63485.firebasestorage.app',
    androidClientId: '879677984368-o89ankjfg4r42obueoookn02m6feon0m.apps.googleusercontent.com',
    iosClientId: '879677984368-qrrivv4v7gh1ebescov6d26slblcd2l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
